import "./globals.css";
import Header from '../components/header/Header'
import Footer from '../components/footer/Footer'
import { ClerkProvider } from "@clerk/nextjs";

export const metadata = {
  title: "Job Listing Portal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
      <body>
        <header>
          <Header />
        </header>
        <main >
          {children}
        </main>
        {/* <footer className="footer">
          <Footer />
        </footer> */}
      </body>
    </html>
    </ClerkProvider>
  );
}
